apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: liveness-http-nginx
spec:
  containers:
  - name: liveness-example-nginx
    image: varoon10/teachingaid:v1
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 4
      periodSeconds: 3
      failureThreshold: 2
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
